<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WercDiscuss\Module'                                 => __DIR__ . '/Module.php',
    'WercDiscuss\Entity\DiscussMessages'                 => __DIR__ . '/src/WercDiscuss/Entity/DiscussMessages.php',
    'WercDiscuss\Form\Discuss'                           => __DIR__ . '/src/WercDiscuss/Form/Discuss.php',
    'WercDiscuss\Form\DiscussFilter'                     => __DIR__ . '/src/WercDiscuss/Form/DiscussFilter.php',
    'WercDiscuss\Model\DiscussMessagesTable'             => __DIR__ . '/src/WercDiscuss/Model/DiscussMessagesTable.php',
    'WercDiscuss\Model\DiscussTable'                     => __DIR__ . '/src/WercDiscuss/Model/DiscussTable.php',
    'WercDiscuss\Service\Discuss'                        => __DIR__ . '/src/WercDiscuss/Service/Discuss.php',
    'WercDiscuss\Service\Factory\DiscussFactory'         => __DIR__ . '/src/WercDiscuss/Service/Factory/DiscussFactory.php',
    'WercDiscuss\Service\Factory\DiscussMessagesFactory' => __DIR__ . '/src/WercDiscuss/Service/Factory/DiscussMessagesFactory.php',
    'WercDiscuss\Service\Factory\DiscussTableFactory'    => __DIR__ . '/src/WercDiscuss/Service/Factory/DiscussTableFactory.php',
    'WercDiscuss\Service\Factory\DiscussWidgetFactory'   => __DIR__ . '/src/WercDiscuss/Service/Factory/DiscussWidgetFactory.php',
    'WercDiscuss\View\Helper\DiscussWidget'              => __DIR__ . '/src/WercDiscuss/View/Helper/DiscussWidget.php',
);
