<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(

    'werc-discuss/_partials/discussion'    => __DIR__ . '/view/werc-discuss/_partials/discussion.phtml',
    'werc-discuss/_partials/messages-tree' => __DIR__ . '/view/werc-discuss/_partials/messages-tree.phtml',
);
